### ISSUE TITLE
Can we not have port mapping?

### ISSUE THREAD

**Issue by DeepBhat** [hcengineering/huly-selfhost#11]
I am hosting on a machine where ports like 9000 and 3000 are already in use and not available. While I modified the compose file generated to change port mapping, the application itself is still making requests to port 3000. I also modified the environment variables to change the port,  but that  didn't work either. 

Would it be a good idea to allow configurable ports instead?

**Comment by aonnikov** [comment]
@DeepBhat thanks for the question, we will consider exposing ports mapping configuration.
- 3000 port is used by `accounts` service, if you want to change it, you should modify the port number in `ACCOUNTS_URL` environment variable and set `ACCOUNT_PORT` env variable to the same value for `account` service.
- 9000 port is used by minio, you need to change `MINIO_ENDPOINT` env variable to `minio:9002` for example and update `minio` container configuration.

**Comment by ja49619** [comment]
> * 9000 port is used by minio, you need to change `MINIO_ENDPOINT` env variable to `minio:9002` for example and update `minio` container configuration.

sorry but your method didnt work, the adapter still tries to connect to port 9000
```
{"adapter":"minio","error":{"address":"192.168.112.2","code":"ECONNREFUSED","errno":-111,"message":"connect ECONNREFUSED 192.168.112.2:9000","port":9000,"stack":"Error: connect ECONNREFUSED 192.168.112.2:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)","syscall":"connect"},"level":"error","message":"failed to init adapter","timestamp":"2024-10-13T08:38:31.928Z","workspaceId":{"name":"w---670b868c-0ebec056e6-43d8e4"}}
{"error":{"address":"192.168.112.2","code":"ECONNREFUSED","errno":-111,"message":"connect ECONNREFUSED 192.168.112.2:9000","port":9000,"stack":"Error: connect ECONNREFUSED 192.168.112.2:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)","syscall":"connect"},"level":"error","message":"Failed to create workspace","timestamp":"2024-10-13T08:38:31.929Z"}
{"level":"error","message":"Unhandled Rejection at:","promise":{},"reason":{"address":"192.168.112.2","code":"ECONNREFUSED","errno":-111,"message":"connect ECONNREFUSED 192.168.112.2:9000","port":9000,"stack":"Error: connect ECONNREFUSED 192.168.112.2:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)","syscall":"connect"},"timestamp":"2024-10-13T08:38:31.931Z"}
```

By the way, the issue of ports is also relevant for me, like the author, 3000 and 9000 are very popular and many applications use them by default. Is it really impossible to select a group of definitely unused ports from ~64000 ports?

**Comment by aonnikov** [comment]
@ja49619 it is definitely possible, will do the change

**Comment by binayab99** [comment]
> @DeepBhat thanks for the question, we will consider exposing ports mapping configuration.
> 
> * 3000 port is used by `accounts` service, if you want to change it, you should modify the port number in `ACCOUNTS_URL` environment variable and set `ACCOUNT_PORT` env variable to the same value for `account` service.
> * 9000 port is used by minio, you need to change `MINIO_ENDPOINT` env variable to `minio:9002` for example and update `minio` container configuration.

I'm having the same issue as @ja49619 . I've changed the ports in config, minio-deployment and minio-service yaml files but still the workspace is trying to connect to port 9000. What am I missing? I've attached the screenshots for reference

![config](https://github.com/user-attachments/assets/529f8ee0-74ea-4232-8418-f1808106abed)
![minio-deployment](https://github.com/user-attachments/assets/161a158e-aa7c-47c8-947e-8b98bb010b2f)
![minio-service](https://github.com/user-attachments/assets/54c3a67c-330c-4071-94b0-69cf74433160)
![error](https://github.com/user-attachments/assets/13fa2114-a72b-4eaa-9c5f-eff9b9ebca68)
