### ISSUE TITLE
New Huly instance, can't sign up "Unknown error: Failed to fetch"

### ISSUE THREAD

**Issue by flotpg** [hcengineering/huly-selfhost#21]
Hi,

I just started a new Huly instance, can't sign up "Unknown error: Failed to fetch".
![CleanShot 2024-07-22 at 11 03 09@2x](https://github.com/user-attachments/assets/3d72ddbf-dd53-4375-bb76-62f1e1abc8ab)

Any hints what I can check?
Many thanks and best regards, Flo.

**Comment by chen5293** [comment]
![fail](https://github.com/user-attachments/assets/389a5e5c-9b4b-403d-9ee9-87be7ac878c0)
I also encountered the same problem

**Comment by felipegoulart** [comment]
I had the same problem.

When running the setup script on my personal PC, I used `localhost` as the IP address, and that resolved the issue.

`./setup.sh localhost`

**Comment by flotpg** [comment]
> I had the same problem.
> 
> When running the setup script on my personal PC, I used `localhost` as the IP address, and that resolved the issue.
> 
> `./setup.sh localhost`

Didn't solve it for me...

**Comment by PhieuDieuVoCuc** [comment]
I observe with the dev tool, and if there are any connection errors for the port in the console tab, I open that port (on the firewall) (for me, it’s 3000 and 3333) with a public IP or an IP that can be accessed from other machines (if not localhost).

**Comment by chen5293** [comment]
You can try to add port 3000 to the network

**Comment by debpalash** [comment]
> You can try to add port 3000 to the network His reverse proxy was not set up. I spent a long time troubleshooting.

hi, did you manage to get it working? if you did what was the chnaged you made?

**Comment by chen5293** [comment]
> > You can try to add port 3000 to the network His reverse proxy was not set up. I spent a long time troubleshooting.
> 
> hi, did you manage to get it working?

Yes, I released a lot of ports on the server side

**Comment by ALOVEROFRAIN** [comment]
> > > You can try to add port 3000 to the network His reverse proxy was not set up. I spent a long time troubleshooting.
> > 
> > 
> > hi, did you manage to get it working?
> 
> Yes, I released a lot of ports on the server side

hi, could you please show me the file "nginx.conf"

**Comment by emreggoktepe** [comment]
Hi,

I'm encountering a persistent error while trying to redirect HTTPS traffic (port 443) to my application listening on port 8087 in Nginx. Despite having a functioning configuration for HTTP (port 80), the HTTPS configuration consistently fails. I've attached both configurations for your review.

Not Working conf;
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name huly.domain.com;
    
    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.key;

    access_log             /var/log/nginx/huly.domain.com-access.log;
    error_log              /var/log/nginx/huly.domain.com-error.log info;

    location / {
        proxy_pass http://localhost:8087;
        include proxy_params;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name huly.domain.com;

    location / {
        return 301 https://huly.domain.com$request_uri;
    }
}


Working conf;

server {
    listen 80;
    listen [::]:80;

    server_name huly.domain.com;

    location / {
        proxy_pass http://localhost:8087;
        include proxy_params;
    }
}

**Comment by egavrilov** [comment]
I would appreciate if you could test nginx config from this PR to be sure I'm not missing anything https://github.com/hcengineering/huly-selfhost/pull/32

**Comment by Hanzo-Huang** [comment]
When I use `http` only, it works will. But it doesn't work on `https`. How can I configure it.

**Comment by kkleber1991** [comment]
> When I use `http` only, it works will. But it doesn't work on `https`. How can I configure it.

Today I stayed all day and identified this too, the question is, did you get a solution? Because I use it in Docker + Dokploy and I couldn't solve it since I use a subdomain managed by Cloudflare and I don't give up ssl.

**Comment by andrewsulisthio** [comment]
> I had the same problem.
> 
> When running the setup script on my personal PC, I used `localhost` as the IP address, and that resolved the issue.
> 
> `./setup.sh localhost`

I ran your command on a freshly installed Ubuntu with Huly currently running with the `Failed to Fetch` issue, and it works, the error is gone and I can proceed to my workspace 👏

**Comment by mortizv** [comment]
I placed the IP and port of Nginx directly in the compose.yml file for the front container.
 - LOVE_ENDPOINT=http://localhost:8087/_love
- ACCOUNTS_URL=http://localhost:8087/_accounts
- REKONI_URL=http://localhost:8087/_rekoni
- CALENDAR_URL=http://localhost:8087/_calendar
- GMAIL_URL=http://localhost:8087/_gmail
- TELEGRAM_URL=http://localhost:8087/_telegram
- STATS_URL=http://localhost:8087/_stats

**Comment by ImLake** [comment]
> > When I use `http` only, it works will. But it doesn't work on `https`. How can I configure it.
> 
> Today I stayed all day and identified this too, the question is, did you get a solution? Because I use it in Docker + Dokploy and I couldn't solve it since I use a subdomain managed by Cloudflare and I don't give up ssl.

Don't mean to bump an old thread, but confirming I am having the same issue in the same stack. I presume we have some form of port fighting match or something. I haven't looked that deeply into it, but I will open an issue on Dokploy for it.

**Comment by lcoll154** [comment]
I am having the same issue and nothing above has fixed it.

**Comment by MERakram** [comment]
> > When I use `http` only, it works will. But it doesn't work on `https`. How can I configure it.
> 
> Today I stayed all day and identified this too, the question is, did you get a solution? Because I use it in Docker + Dokploy and I couldn't solve it since I use a subdomain managed by Cloudflare and I don't give up ssl.

I'm using dokploy too, any solutions months later...?

**Comment by shali1995** [comment]
what an anoyying proeject, what so hard aboyt making it ez to fucking self host, pure bullshit oh my god.
