### ISSUE TITLE
UPLOAD_URL is wrong for transactor

### ISSUE THREAD

**Issue by Telokis** [hcengineering/huly-selfhost#26]
In the `transactor` service ([Here](https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L140)), there is the following line:
```
      - UPLOAD_URL=http://${SERVER_ADDRESS}/files
```

which is mising the port to properly work.  

I could make a PR to fix it but I have no idea what the correct service is supposed to be.

The other ocurrences of the `UPLOAD_URL` only specify `/files` as the value. ([front](https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L83) and [collaborator](https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L107)).  
Either this is the proper value and `transactor` should match or they are both wrong and should specify the full URL like `transactor`.

**Comment by aonnikov** [comment]
Thanks for reporting this. You contribution would be welcome. `/files` API is served by the 'front' service, so the same port as for FRONT_URL should be used (8087 by default): https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L136

**Comment by aonnikov** [comment]
UPLOAD_URL is not used in transactor anymore.
