### ISSUE TITLE
Run without Nginx

### ISSUE THREAD

**Issue by Digital39999** [hcengineering/huly-selfhost#53]
Is there a way to run huly without nginx and let us actually take care of access to it and securing it?
Forcing us to use nginx and even worse if I already have one is really inconvenient.

**Comment by jondef** [comment]
You can use traefik is you want or any other reverse proxy

**Comment by Digital39999** [comment]
Well is there a way to run it without a proxy at all? Why is proxy needed?

**Comment by jondef** [comment]
I don't think running this project without a reverse proxy is a good idea, because it's a microservice architecture- there's like 6 of them or more, and so you need a reverse proxy to forward the incoming requests to the correct container based on the port and url. What's your setup you currently have?

**Comment by Digital39999** [comment]
I didn't realize it was actually running multiple different services, I thought it was just a single service that coordinates the endpoints. Makes sense now why it needs to have endpoints rewritten. I was thinking it would be easier to self-host, especially if it's running on a local server under a NAS rather than a public VPS with a dedicated IP.

**Comment by ja49619** [comment]
> I didn't realize it was actually running multiple different services, I thought it was just a single service that coordinates the endpoints. Makes sense now why it needs to have endpoints rewritten. I was thinking it would be easier to self-host, especially if it's running on a local server under a NAS rather than a public VPS with a dedicated IP.

no matter where you run on nas or vps. for you as a user there will be only one endpoint - ip:8087. 

In general, the question you raised is relevant. There are more convenient and modern reverse proxies, but the automatic installation script imposes the dinosaur nginx. Just give the choice “with or without a proxy”, and then we’ll figure out what to redirect through.

**Comment by Digital39999** [comment]
> In general, the question you raised is relevant. There are more convenient and modern reverse proxies, but the automatic installation script imposes the dinosaur nginx. Just give the choice “with or without a proxy”, and then we’ll figure out what to redirect through.

You're absolutely right. The only confusion I have is that in the README, it mentions Nginx is running as a service via `systemctl`, rather than being set up in the Docker Compose file, which would route everything together. I wouldn't want to install anything directly on my system — I prefer to keep everything contained within a single Docker Compose setup or in multiple containers.

**Comment by veryCrunchy** [comment]
This is possible with #36
Just ignore the nginx part.
