### ISSUE TITLE
Disable of Self Sign-Up

### ISSUE THREAD

**Issue by tobiasreichel** [hcengineering/huly-selfhost#55]
Hey Everyone 

i know this is a relative Fresh Software

so my Question is there a way to disable the Self Sign-Up so only way to get in is via an invite 

Greets

**Comment by lexiv0re** [comment]
Hi @tobiasreichel, thanks for your interest in Huly. We'll be working on this feature soon: https://github.com/hcengineering/platform/issues/6880.

**Comment by Mirasaki** [comment]
I noticed this issue has been completed on /platform - is there any ETA for when it will be merged into huly-selfhost? No rush of course, just excited to use this :)

**Comment by lexiv0re** [comment]
Available in v0.6.333 https://github.com/hcengineering/huly-selfhost?tab=readme-ov-file#disable-sign-up

**Comment by Mirasaki** [comment]
Amazing, really glad to see this implemented so fast - thank you!
