### ISSUE TITLE
Unknown error: JSON.parse: unexpected character at line 1 column 1 of JSON data

### ISSUE THREAD

**Issue by ja49619** [hcengineering/huly-selfhost#59]
Hello,
I installed huly v0.6.313 using docker-compose taken from here
after logging into the application and trying to register I get this error:

`Unknown error: JSON.parse: unexpected character at line 1 column 1 of JSON data`

![Снимок экрана 2024-10-13 194714](https://github.com/user-attachments/assets/9a1fb45c-f3fe-4855-aee5-22bef2aa0582)

here is log of huly-workspace container:
`{"err":{"message":"Unexpected token 'I', \"Internal S\"... is not valid JSON","stack":"SyntaxError: Unexpected token 'I', \"Internal S\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)\n    at successSteps (node:internal/deps/undici/undici:5454:27)\n    at fullyReadBody (node:internal/deps/undici/undici:4381:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async consumeBody (node:internal/deps/undici/undici:5463:7)\n    at async getPendingWorkspace (/usr/src/app/bundle.js:253:441072)\n    at async /usr/src/app/bundle.js:460:146690\n    at async rRt.start (/usr/src/app/bundle.js:460:146629)"},"level":"error","message":"Error getting pending workspace:","timestamp":"2024-10-13T15:53:14.672Z"}`

Does anyone know what the problem is and how to fix it?

**Comment by ja49619** [comment]
ok I solved the problem, I'll write here in case it helps someone.
the problem was that my processor does not support AVX, so mongo 7 could not start.
solution - change docker-compose:
```
...
mongodb:
  image: "mongo:4.4"
...
```

**Comment by ja49619** [comment]
In general, rolling back to the old version will allow you to install workspace, but you will still not be able to use the services due to conflicts with new functions introduced after Mongo 5

`{"error":{"code":9,"codeName":"FailedToParse","errorResponse":{"code":9,"codeName":"FailedToParse","errmsg":"$lookup with 'pipeline' may not specify 'localField' or 'foreignField'","ok":0},"message":"$lookup with 'pipeline' may not specify 'localField' or 'foreignField'","ok":0,"stack":"MongoServerError: $lookup with 'pipeline' may not specify 'localField' or 'foreignField'\n    at _Connection.sendCommand (/usr/src/app/bundle.js:150603:21)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _Connection.command (/usr/src/app/bundle.js:150624:26)\n    at async _Server.command (/usr/src/app/bundle.js:152246:25)\n    at async AggregateOperation.executeCommand (/usr/src/app/bundle.js:121816:16)\n    at async AggregateOperation.execute (/usr/src/app/bundle.js:123606:16)\n    at async tryOperation (/usr/src/app/bundle.js:121693:18)\n    at async executeOperation (/usr/src/app/bundle.js:121610:16)\n    at async _AggregationCursor._initialize (/usr/src/app/bundle.js:158556:26)\n    at async _AggregationCursor.cursorInit (/usr/src/app/bundle.js:158353:25)"},"level":"error","message":"error handle request","request":{"id":39,"method":"findAll","params":["tracker:class:Issue",{"kind":"tracker:taskTypes:Issue","space":"tracker:project:DefaultProject","status":"tracker:status:Backlog"},{"limit":50,"lookup":{"_id":{"subIssues":"tracker:class:Issue"},"attachedTo":"tracker:class:Issue"},"sort":{"modifiedOn":-1}}],"time":1728877070923},"timestamp":"2024-10-14T03:38:19.344Z"} `

so there is only one way out - change the processor with AVX support 😞 and install Mongo 7 as in the developer instructions

**Comment by frogzjx** [comment]
Hi @ja49619 

Use 'ghcr.io/flakybitnet/mongodb-server'. This MongoDB is compiled with an older compiler, and it can run on CPUs that do not support AVX instructions.

```
mongodb:
    image: "ghcr.io/flakybitnet/mongodb-server:7.0.16-fb2"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped
```
