### ISSUE TITLE
Problem kube deployement

### ISSUE THREAD

**Issue by ed-auvinet** [hcengineering/huly-selfhost#60]
I am using huly self-hosted with the kube directory deployement for kubernetes.

Both transator and account crash and tell with the logs that they need DB_URL.

This reference does not exist in the config map.

What should I had or configure.

Thanks a lot in advance,

Best regards,

**Comment by ed-auvinet** [comment]
Finally I found out with the platform code

I added DB_URL in the config_map

DB_URL: 'mongodb://mongodb:27017'

and :
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: huly-config
                  key: DB_URL

in both account-deployemnt.yaml and transactor-deployement.yaml

Now it deploys nicely

**Comment by aonnikov** [comment]
@ed-auvinet thanks for reporting this and glad that you managed to find the solution by yourself. This env variable is a recent change related to PostgreSQL support added to Huly. I'm planning to update our configuration examples with proper env variables for the latest Huly version.

**Comment by 0xtejas** [comment]
@aonnikov Are you supporting Postgres additionally or removing it? I see the other repo and they are commented out. When I tried deploying the code from this repo, I used the MongoDB URL as the DB_URL.

**Comment by aonnikov** [comment]
@0xtejas Postgres is supposed to be used instead of MongoDB. But currently we still have couple of services that use MongoDB directly and that's the reason why we have both DB_URL and MongoDB URL env variables.

**Comment by 0xtejas** [comment]
@aonnikov 

Meanwhile, can I make a PR as a placeholder to use the MongoDB URL in the DB_URL variable until we have Postgres compatibility? 

> Finally I found out with the platform code
> 
> I added DB_URL in the config_map
> 
> DB_URL: 'mongodb://mongodb:27017'
> 
> and : - name: DB_URL valueFrom: configMapKeyRef: name: huly-config key: DB_URL
> 
> in both account-deployemnt.yaml and transactor-deployement.yaml
> 
> Now it deploys nicely

**Comment by aonnikov** [comment]
The problem has been fixed with https://github.com/hcengineering/huly-selfhost/pull/73
