### ISSUE TITLE
I published it a day ago. All my data was deleted. It shows an account not found error.

### ISSUE THREAD

**Issue by eymel** [hcengineering/huly-selfhost#72]
Hello, I shared the project on my own subdomain. Two people and I tested it generally, and it was working. I created a few projects and issues. This morning, when I woke up, I received an account not found error while trying to log in with the same email and password. All my data seems to be deleted. 

Is this a known issue? I couldn't understand why this happened. Could you please help me?

**Comment by lexiv0re** [comment]
Hello @eymel , thanks for your interest in Huly! Could you check the contents of your database directly connecting to it with some DB client? Will you be able to see some records there (e.g. in `account` db `account` or `workspace` collections) ?

**Comment by eymel** [comment]
When I check the database, no data is visible. There were two users yesterday, and now only the single user I created this morning is visible.

**Comment by lexiv0re** [comment]
No problem with that, I'm glad you figured it out! We've seen this issue reported before.
Please take a closer look at the security section of the readme: https://github.com/hcengineering/huly-selfhost?tab=readme-ov-file#security to prevent similar issues in the future.
