### ISSUE TITLE
Gmail Password Recovery Internal Server Error

### ISSUE THREAD

**Issue by F04C** [hcengineering/huly-selfhost#74]
services:

  gmail:
    image: hardcoreeng/gmail:${HULY_VERSION}
    links:
      - mongodb
      - minio
    ports:
      - 8088:8087
    environment:
      - SERVER_PORT=8088
      - SERVER_SECRET=${HULY_SECRET}
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3001
      - FRONT_URL=http://${SERVER_ADDRESS}:8088
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REDIRECT_URI=${GMAIL_REDIRECT_URI}
      - GMAIL_SCOPES=${GMAIL_SCOPES}
      - EMAIL_SERVICE_URL=http://${SERVER_ADDRESS}:8088
      - MONGO_URI=mongodb://mongodb:27017 
      - SECRET=${HULY_SECRET}
      - Credentials=${Credentials}
      - WATCH_TOPIC_NAME=email_notifications
    restart: unless-stopped
    
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - db:/data/db
    ports:
      - 27017:27017  
    restart: unless-stopped

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9020:9020
      - 9021:9021  
    volumes:
      - files:/data
    restart: unless-stopped

  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200  
    environment:
      - ELASTICSEARCH_PORT_NUMBER=${ELASTICSEARCH_PORT_NUMBER}
      - BITNAMI_DEBUG=${BITNAMI_DEBUG}
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - http.cors.enabled=${CORS_ENABLED}
      - http.cors.allow-origin=${CORS_ALLOW_ORIGIN}
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    links:
      - mongodb
      - minio
      - gmail
    ports:
      - 3030:3001
    environment:
      - SERVER_PORT=3030
      - SERVER_SECRET=${HULY_SECRET}
      - MONGO_URL=mongodb://mongodb:27017
      - DB_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3334;ws://${SERVER_ADDRESS}:3334
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - FRONT_URL=http://front:8080
      - MODEL_ENABLED=${MODEL_ENABLED}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3001
      - ACCOUNT_PORT=${ACCOUNT_PORT}
      - EMAIL_SERVICE_URL=http://${SERVER_ADDRESS}:8088
    depends_on:
      - gmail
    restart: unless-stopped

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    links:
      - mongodb
      - minio
    environment:
      - SERVER_SECRET=${HULY_SECRET}
      - MONGO_URL=mongodb://mongodb:27017
      - DB_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3334;ws://${SERVER_ADDRESS}:3334
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - MODEL_ENABLED=${MODEL_ENABLED}
      - ACCOUNTS_URL=http://account:3001
      - NOTIFY_INBOX_ONLY=${NOTIFY_INBOX_ONLY}
      - EMAIL_SERVICE_URL=http://${SERVER_ADDRESS}:8088
    depends_on:
      - gmail
    restart: unless-stopped

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    links:
      - mongodb
      - minio
      - elastic
      - collaborator
      - transactor
      - gmail
    ports:
      - 8100:8087
    environment:
      - SERVER_PORT=8087
      - SERVER_SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3030
      - REKONI_URL=http://${SERVER_ADDRESS}:4004
      - CALENDAR_URL=http://${SERVER_ADDRESS}:8095
      - GMAIL_URL=http://gmail:8087
      - TELEGRAM_URL=http://${SERVER_ADDRESS}:8086
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9201
      - COLLABORATOR_URL=ws://${SERVER_ADDRESS}:3080 
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - MONGO_URL=mongodb://mongodb:27017
      - TITLE=${TITLE}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - LAST_NAME_FIRST=${LAST_NAME_FIRST}
    depends_on:
      - gmail
    restart: unless-stopped

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    links:
      - mongodb
      - minio
      - transactor
    ports:
      - 3080:3080
    environment:
      - COLLABORATOR_PORT=3080
      - SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://account:3001
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
    restart: unless-stopped

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    links:
      - mongodb
      - elastic
      - minio
      - account
    ports:
      - 3334:3334
    environment:
      - SERVER_PORT=3334
      - SERVER_SECRET=${HULY_SECRET}
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:9201
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME}
      - MONGO_URL=mongodb://mongodb:27017
      - DB_URL=mongodb://mongodb:27017
      - METRICS_CONSOLE=${METRICS_CONSOLE}
      - METRICS_FILE=${METRICS_FILE}
      - STORAGE_CONFIG=minio|minio?accessKey=${MINIO_ACCESS_KEY}&secretKey=${MINIO_SECRET_KEY}
      - REKONI_URL=http://rekoni:4004
      - FRONT_URL=http://${SERVER_ADDRESS}:8088
      - ACCOUNTS_URL=http://account:3001
      - LAST_NAME_FIRST=${LAST_NAME_FIRST}
    restart: unless-stopped

  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    ports:
      - 4004:4004
    environment:
      - SECRET=${HULY_SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped

volumes:
  db:
  files:
  elastic:
  etcd:
  
  
  
  Gmail integration still not working. 
  
  
  
![image](https://github.com/user-attachments/assets/e54f50bb-f6c5-4eb0-a62b-813be5afc5ec)

Can't seem to find a solution since there's no documentation for gmail service yet.

**Comment by aonnikov** [comment]
@F04C please look at this pull request, it adds example of email service configuration:
https://github.com/hcengineering/huly-selfhost/pull/38
