### ISSUE TITLE
Can't upload files: minio returns "NoSuchBucket" and server dies with 500

### ISSUE THREAD

**Issue by daidonpah** [hcengineering/huly-selfhost#75]
Fresh install, everything seems to work fine, but when I tried uploading files (e.g. into a ticket) I receive an error message:

<img width="251" alt="image" src="https://github.com/user-attachments/assets/3e176b69-8589-41ff-97c1-dff1eafc9665">

When I execute `docker logs front-1` I get:

```
{"amzId2":"someId","amzRequestid":"someId","bucketname":"w-name-domain-6710387a-58b307668a-a9835d","code":"NoSuchBucket","hostid":"someId","key":"someKey","level":"error","message":"The specified bucket does not exist","name":"S3Error","requestid":"someId","resource":"/w-name-domain-6710387a-58b307668a-a9835d/6aa69d05-5d16-4884-acb6-509dee4d5399","timestamp":"2024-10-16T22:42:26.272Z"}
{"level":"info","message":"::ffff:172.22.0.1 - POST /files HTTP/1.1 500 - - 9.220 ms\n","name":"requests","timestamp":"2024-10-16T22:42:26.272Z"}
```

I tried creating the bucket in the minio container:

`mc mb w-name-domain-6710387a-58b307668a-a9835d`

But this didn't help. I am assuming buckets should be created automatically? Am I missing something? 🙂 

Logs on the minio container are empty, except for a warning with default credentials

EDIT: I got it fixed running 
`mc mb data/w-name-domain-6710387a-58b307668a-a9835d`

But still, I should not have to do this manually, no?

**Comment by aonnikov** [comment]
@daidonpah thanks for reporting this.
You are right, you are not supposed to create buckets by yourself. Normally, bucket is created when you create a workspace.

I suppose that logs might be in the `account` or `workspace` containers.

**Comment by daidonpah** [comment]
Unfortunately there was nothing helpful:

```
# docker logs workspace-1
Logging also into console development true
{"level":"info","message":"####################################################################################################################","timestamp":"2024-10-16T22:36:50.576Z"}
{"level":"info","message":"########################SplitLogger workspace initialized: 2024-10-16T22:36:50.577Z###########################","timestamp":"2024-10-16T22:36:50.577Z"}
Starting workspace service in region: DEFAULT for operation: all for version: 0.6.313 with brandings: {}
# docker logs account-1
Logging also into console development true
{"level":"info","message":"####################################################################################################################","timestamp":"2024-10-16T22:36:49.820Z"}
{"level":"info","message":"########################SplitLogger account initialized: 2024-10-16T22:36:49.821Z###########################","timestamp":"2024-10-16T22:36:49.821Z"}
Starting account service with brandings:  {}
server started on port 3000
```

**Comment by aonnikov** [comment]
Thanks! I tried to reproduce the issue but could not.
