### ISSUE TITLE
Integrations not working (GitHub, Telegram, Gmail, etc)

### ISSUE THREAD

**Issue by zoologov** [hcengineering/huly-selfhost#90]
Hello!
Please tell me how to integrate with github? I got 404 page when i try to install github app and when i try to log in using personal profile.
<img width="987" alt="image" src="https://github.com/user-attachments/assets/cb5107d2-7019-4d2e-8d55-cfcc99d33bdb">

**Comment by zoologov** [comment]
Where set githubApp?
<img width="774" alt="image" src="https://github.com/user-attachments/assets/a30b5b98-ae36-456e-a2cd-16ba1db18a8a">

**Comment by zoologov** [comment]
After reviewing the main repository’s code, I understood how all integrations work and set up the GitHub integration. I am closing the request, and when I have some free time, I will make a pull request with the configuration.

**Comment by shanzez** [comment]
I would love some guidance on this and learn from your efforts, if you don't mind.  We're on the latest huly version and don't have any of the integrations working.

**Comment by shanzez** [comment]
Even if you wanted to dump your notes here, @zoologov, I would be glad to document what you have and make any changes, giving you credit of course.

**Comment by volkovmqx** [comment]
@shanzez  

After analyzing the codebase (platform) and relevant documentation:
- https://github.com/hcengineering/huly-selfhost/issues/1
- https://github.com/hcengineering/platform/tree/develop/services/github/pod-github

Here's how to properly configure Github integration:

## Steps

1. Create a GitHub App and configure it according to the pod readme (remote server setup doesn't require smee configuration)

2. Deploy the GitHub Docker Compose image as shown in [this comment](https://github.com/hcengineering/huly-selfhost/issues/1#issuecomment-2418428777)

3. Configure the frontend with these environment variables:
```
GITHUB_APP
GITHUB_CLIENTID
GITHUB_URL=http${SECURE:+s}://${HOST_ADDRESS}/_github
```

## Nginx Configuration

Add this location block to your Nginx configuration:
```nginx
location /_github {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    rewrite ^/_github(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:3500/;
}
```

Unfortunately, I don't have enough time right now to propose a complete PR for a comprehensive guide. However, I'll keep monitoring this issue and would be happy to help review or provide input if someone else takes on writing the documentation. Feel free to tag me if you need any clarification about the setup process. Cheers!
