### ISSUE TITLE
after DISABLE_SIGNUP=true UI still shows signup screen

### ISSUE THREAD

**Issue by etranger7** [hcengineering/huly-selfhost#92]
I added
```
DISABLE_SIGNUP=true
```
under both account and front services as instructed in here:
https://github.com/hcengineering/huly-selfhost#disable-sign-up

The signup tab/screen is still there.
Shouldn't this setting under "front" result in preventing that form from being displayed?

**Comment by lexiv0re** [comment]
Hello @etranger7 . Yes, you are right. In this release there was an issue with wiring the config value to the UI components. It's been already fixed and should start working as expected in the next release. The sign up will be hidden from the UI as well not only disabled on the service side.

**Comment by etranger7** [comment]
Thank you for fixing it and your quick response 😃
